### PR TITLE
Preben bugfix additions

### PR DESCRIPTION
**Pull request by plemsoft**
PE: Fix for - Objects can displays wrong, if dbo is generated outside importer.
Original skin weight is not used but generated, this can give animation problems.
Also make sure dbo have all FVF semantic names when using skipfvfconvert=1.
https://github.com/TheGameCreators/GameGuruRepo/issues/104
https://github.com/TheGameCreators/GameGuruRepo/issues/54

PE: fix for - Black weird textures. 
Tangent is not calculated correct in ComputeTangentBasisEx, perhaps because we cant use the fixtangent flag that ruin bones ? , this calculation have been moved.
Tangent calculation added to vertex shaders.
https://github.com/TheGameCreators/GameGuruRepo/issues/85
https://github.com/TheGameCreators/GameGuruRepo/issues/54

Some textures do not have _d,_color,_albedo , so always reset.
https://github.com/TheGameCreators/GameGuruRepo/issues/115
https://github.com/TheGameCreators/GameGuruRepo/issues/71

PE: fix for - Models with single .png texture problem 
https://github.com/TheGameCreators/GameGuruRepo/issues/115

Weapons - Jetpack Hud Missing
https://github.com/TheGameCreators/GameGuruRepo/issues/44

Weapons - Soldiers without Guns in Hand
https://github.com/TheGameCreators/GameGuruRepo/issues/43

Editor - Invisible Uber Solider:
https://github.com/TheGameCreators/GameGuruRepo/issues/82

Entities not visible sometimes.
https://github.com/TheGameCreators/GameGuruRepo/issues/70

Models vanishing
https://github.com/TheGameCreators/GameGuruRepo/issues/103

Importer do not display object correct
https://github.com/TheGameCreators/GameGuruRepo/issues/101

### CODE REVIEW

**Comment by cybernescence** [comment]
Brilliant fixes Preben - Cheers! One thing I noticed with the jet pack is that when wearing and look down at ground can see the end of the HUD arms and jet pack - can remove this with the weapon FOV slider but I'm not sure it was like this before - is it clipping on the camera? Or do we just need to lower FOV?

**Comment by plemsoft** [comment]
Hi cybernescence :)

Thanks for testing, and i fixed the HUD from getting clipped by the camera near plane.

Believe your the only one around here testing braces , that is so great :) , i think gg is getting pretty stable now just wondering what else is a must fix before a actually release can be considered, do you got any MUST fix issues ?

**Comment by LeeBamberTGC** [comment]
Excellent fixes, thanks very much!!  I will see about getting a beta build created before I soon off to GDC.

**Comment by plemsoft** [comment]
Thanks :) , please also approve the new PBR Illumination maps for the beta, i just made a new pull.

**Pull request merged**
