### PR TITLE
Update to M-Game.cpp-users now use SHIFT+F1-F4 keys to trigger the Li…

### PR DESCRIPTION
**Pull request by redagent101**
…ghtmapper

### CODE REVIEW

**Comment by plemsoft** [comment]
Checked your changes , we have 2 shift keys so perhaps this is better:

```
				if (  KeyState(g.keymap[59]) == 1 && (KeyState(g.keymap[42]) | KeyState(g.keymap[54])))  g.lmlightmapnowmode = 1;
				if (  KeyState(g.keymap[60]) == 1 && (KeyState(g.keymap[42]) | KeyState(g.keymap[54])))  g.lmlightmapnowmode = 2;
				if (  KeyState(g.keymap[61]) == 1 && (KeyState(g.keymap[42]) | KeyState(g.keymap[54])))  g.lmlightmapnowmode = 3;
				if (  KeyState(g.keymap[62]) == 1 && (KeyState(g.keymap[42]) | KeyState(g.keymap[54])))  g.lmlightmapnowmode = 4;

```
Also all the images quick-help,testgamelayout and the doc need to reflect this change, not sure if any hard copy exist of the keyboard layout / doc ?

Perhaps it would be better if you make this a setup.ini option until if/when all images/doc ... is updated ?

Anyway i had plenty of these "coffee breaks" so a nice way to prevent accidental lightmapping :)

**Comment by redagent101** [comment]
ah yes, of course, silly me,  I did it all too quickly.  The images can be found here: C:\Program Files (x86)\Steam\steamapps\common\Game Guru\Files\languagebank\english\artwork

Anyway, I can update the code.

**Comment by plemsoft** [comment]
Ohh the single "|" was intended as a bitwise OR , i see you used a logical OR , both ways should work :)

If you changed the images to reflect the change, perhaps you should also add the files to this pull.

If not i think you must make this a setup.ini option for Lee to approve it, but i could be wrong ? Lee ?

**Comment by redagent101** [comment]
I think I must be in my own dreamworld.  Ah yes, I can revert to using the exclusive OR "|" if it's preferable.  I think I changed it to "||" as I was getting errors but I think I realised it was probably down to unbalanced brackets.  I did start to edit 1 of the pics to show "shift" should be used.  If Lee is happy for me to change all the other pics, I can.  Not sure if there was an artist assigned to do these kinds of artwork.

**Comment by plemsoft** [comment]
> if it's preferable
Don't matter :)

> Not sure if there was an artist assigned to do these kinds of artwork.

Looks like the logo also need to be changed , so perhaps Lee need to change them anyway ? :)

**Comment by redagent101** [comment]
I could look at the code that handles the reading in of the GG settings.ini file and add a option.  Not sure what Lee thinks or just leave as is.

**Pull request closed without merging**
