### PR TITLE
Water tab panel with lua commands

### PR DESCRIPTION
**Pull request by HierToo**
Added a tab panel for changing waters shader settings ingame
Added lua commands for water shader settings
Fixed a describtion bug in the global.lua
Added a script syntax list for the lua water commands

### CODE REVIEW

**Comment by Granada1** [comment]
Great addition

**Comment by LeeBamberTGC** [comment]
Hi HierToo, is this branch complete with no more additions?  Just want to make sure before I merge it to the master and delete this branch, thanks!

**Comment by HierToo** [comment]
This branch is complete. I have no addition anymore on my harddrive

**Comment by LeeBamberTGC** [comment]
It took an age, but finally managed to find time to test and integrate your water slider panel, looks amazing, thanks!

**Pull request merged**
